### ISSUE TITLE
tagName is not always defined

### ISSUE THREAD

**Issue by bkahlert** [jaschaephraim/jquery-shift-heading-levels#1]
If the input is a text node the tagName is not defined.
This leads to error "Uncaught TypeError: Cannot read property 'match' of undefined" (see attachment).
![screen shot 2015-09-10 at 03 51 33](https://cloud.githubusercontent.com/assets/1170054/9778379/c917cd3a-576f-11e5-898f-8984c8d23864.png)

**Comment by jaschaephraim** [comment]
Thanks! Fixed v1.0.3

**Comment by bkahlert** [comment]
Thanks. Problem fixed. Works now!
